# Generated by Django 4.1.3 on 2023-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creator_user',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
