# Generated by Django 4.1.3 on 2023-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_creator_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='creator_user',
            new_name='creator_username',
        ),
    ]
