# Generated by Django 4.1.3 on 2023-03-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='username',
        ),
    ]
